apiVersion: v1
kind: Pod
metadata:
  labels:
    run: test
  name: test
spec:
  containers:
  - image: nginx
    name: nginx
    volumeMounts:
      - mountPath: /tmp
        name: local-dir
  - image: alpine
    name: alpine
    command: ["sleep"]
    args: ["3600"]
    volumeMounts:
      - mountPath: /tmp
        name: local-dir
  volumes:
  - name: local-dir
    emptyDir:
      sizeLimit: 50Mi
